# Generated by Django 5.0.3 on 2024-11-14 07:29

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blogpost_published_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, help_text='Upload an image for the About page (Recommended size: ~200x200 pixels).', null=True, upload_to='about_images/')),
                ('bio', ckeditor_uploader.fields.RichTextUploadingField(help_text='Enter your bio with rich text formatting.')),
            ],
            options={
                'verbose_name': 'About Page',
                'verbose_name_plural': 'About Pages',
            },
        ),
    ]
