# Generated by Django 5.0.3 on 2024-11-14 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_about'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
    ]
