# Generated by Django 5.0.3 on 2024-11-14 16:22

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_delete_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, help_text='Upload an image for the About page (e.g., a profile picture).', null=True, upload_to='blog_images/')),
                ('bio', ckeditor_uploader.fields.RichTextUploadingField(help_text='Enter your bio with rich text formatting.')),
                ('email_primary', models.EmailField(help_text='Primary contact email.', max_length=254)),
                ('email_secondary', models.EmailField(blank=True, help_text='Secondary contact email (optional).', max_length=254)),
            ],
            options={
                'verbose_name': 'About Page',
                'verbose_name_plural': 'About Pages',
            },
        ),
    ]
